### ISSUE TITLE
non-scaling-stroke

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#54]
http://nponeccop.livejournal.com/538526.html?thread=4772766#t4772766

может всё-таки стоит воткнуть в CSS что-то типа
```css
path { vector-effect: non-scaling-stroke; }
```
чтобы избежать этих адовых «лент» при зуме?
